Library Management System/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Library_Management_System.Services;
using Library_Management_System.ViewModels;
using Library_Management_System.Models;
using System.Text.Json;

namespace Library_Management_System.Controllers
{
    public class AuthController : Controller
    {
        private readonly ILogin _loginService;
        private readonly IHttpContextAccessor _contextAccessor;

        public AuthController(ILogin login, IHttpContextAccessor httpContextAccessor)
        {
            _loginService = login;
            _contextAccessor = httpContextAccessor;
        }

        /// <summary>
        /// Display the login form. Logged user cannot navigate to this page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            ISession session = HttpContext.Session;
            if (session.GetString("user") == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        /// <summary>
        /// Handle login logic
        /// </summary>
        /// <param name="loginView"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult DoLogin(LoginViewModel loginView)
        {
            User? loggedUser = _loginService.Login(loginView.Username, loginView.Password);
            if (loggedUser != null) // login sucess
            {
                // TODO: set user object to session
                ISession session = _contextAccessor.HttpContext.Session;
                session.SetString("user", JsonSerializer.Serialize(loggedUser));
                if(loggedUser.Role == 1)
                {
                    return RedirectToAction("Index", "Admin");
                }

                if(loggedUser.Role == 2)
                {
                    return RedirectToAction("Index", "Home");
                }

                return NotFound();
            }
            else // login failed
            {
                ViewBag.Message = "Wrong username or password";
                return View("Index");
            }
        }

        [HttpGet]
        public IActionResult Logout()
        {
            ISession session = _contextAccessor.HttpContext.Session;
            session.Clear();
            return RedirectToAction("Index", "Home");
        }

        //[HttpGet]
        //public IActionResult RegisterIndex()
        //{

        //}

        //[HttpPost]
        //public IActionResult DoRegister()
        //{

        //}

    }
}

Library Management System/Controllers/BookController.cs
using Library_Management_System.Models;
using Library_Management_System.Services;
using Library_Management_System.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Text.Json;

namespace Library_Management_System.Controllers
{
    public class BookController : Controller
    {

        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IBookServices _bookServices;
        private readonly IBookDetailServices _bookDetailServices;

        public BookController(IHttpContextAccessor httpContextAccessor, IBookDetailServices bookDetailServices, IBookServices bookServices) 
        {
            _httpContextAccessor = httpContextAccessor;
            _bookServices = bookServices;
            _bookDetailServices = bookDetailServices;
        }
        public IActionResult Index()
        {
            ISession session = _httpContextAccessor.HttpContext.Session;
            if (session.GetString("user") == null) // not logged in user are not allowed to access
            {
                return RedirectToAction("Index", "Home");
            }

            User loggedUser = JsonSerializer.Deserialize<User>(session.GetString("user"));
            if (loggedUser.Role != 1) // only admin role = 1 is allowed
            {
                return RedirectToAction("Index", "Home");
            }
            /*
             
             */
            List<Book> books = _bookServices.GetBooks().ToList();
            List<BookViewModel> bookViewModels = new List<BookViewModel>();
            foreach (var item in books)
            {
                BookDetail bookDetail = _bookDetailServices.GetBookDetailById(item.Id);
                //GetBookDetailById method is being called inside a loop in the Index method of your BookController.
                //If _bookServices.GetBooks() in the Index method is returning an IQueryable
                //and you’re not materializing the results (with ToList() or ToArray(), for example)
                //before you start the loop, then the DataReader for this operation could still be open
                //when GetBookDetailById is called, leading to the error.
                //solution(use list instead of Ienumerable.
                BookViewModel bookViewModel = new BookViewModel
                {
                    Id = item.Id,
                    Title = item.Title,
                    ISBN = item.Isbn,
                    edition = item.Edition,
                    publisher = item.Publisher,
                    location = bookDetail.BookLocation,
                    num_of_copies = bookDetail.NumOfCopies,
                    format = bookDetail.Format,
                };
                bookViewModels.Add(bookViewModel);
            }
            
            return View(bookViewModels);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        /// Doing add book and book detail to the database. [Bind] attributed is used to prevent over-posting attack, 
        /// book's id will be auto generated by getting max id available in the database, and not from form
        /// </summary>
        /// <param name="book"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create([Bind("Title, ISBN, edition, publisher, description, location, num_of_copies, format")] BookAddModel bookAddModel)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.SelectMany(x => x.Value.Errors.Select(p => p.ErrorMessage)).ToList();

                foreach (var error in errors)
                {
                    Console.WriteLine(error);
                }
            }
            if (ModelState.IsValid) { 
                Book book = new Book
                {
                    Id=_bookServices.GetBookCount()+1,
                    Title = bookAddModel.Title,
                    Isbn = bookAddModel.ISBN,
                    Edition = bookAddModel.edition,
                    Publisher = bookAddModel.publisher,
                    Description =bookAddModel.description,
                };
                BookDetail bookDetail = new BookDetail
                {
                    BookId = book.Id,
                    BookLocation = bookAddModel.location,
                    NumOfCopies = bookAddModel.num_of_copies,
                    Format = bookAddModel.format,
                };
            _bookServices.AddBook(book);
            _bookDetailServices.AddBookDetail(bookDetail);
            }
            return RedirectToAction("Index");
        }

    }
}

Library Management System/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor httpContextAccesor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <h1 class="title1 text-center"> LMS</h1>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library_Management_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-center" asp-area="" asp-controller="Home" asp-action="Index">Library Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1" style="margin-left:75%">
                        @if (httpContextAccesor.HttpContext.Session.GetString("user") == null)
                        {
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-controller="Auth" asp-action="Index">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Library_Management_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>